// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Caso3Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() throws MalformedURLException {
    driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), DesiredCapabilities.chrome());
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void caso3() {
    // Test name: caso#3
    // Step # | name | target | value
    // 1 | open | http://automationpractice.com/index.php | 
    driver.get("http://automationpractice.com/index.php");
    // 2 | setWindowSize | 1376x744 | 
    driver.manage().window().setSize(new Dimension(1376, 744));
    // 3 | click | css=.login > font > font | 
    driver.findElement(By.cssSelector(".login > font > font")).click();
    // 4 | click | css=.page-heading > font > font | 
    driver.findElement(By.cssSelector(".page-heading > font > font")).click();
    // 5 | click | css=.navigation_page > font > font | 
    driver.findElement(By.cssSelector(".navigation_page > font > font")).click();
    // 6 | click | id=email_create | 
    driver.findElement(By.id("email_create")).click();
    // 7 | type | id=email_create | fajardoj8\n6b@gmail.com
    driver.findElement(By.id("email_create")).sendKeys("fajardoj8\\n6b@gmail.com");
    // 8 | click | css=#SubmitCreate font > font | 
    driver.findElement(By.cssSelector("#SubmitCreate font > font")).click();
    // 9 | mouseOver | css=#SubmitCreate font > font | 
    {
      WebElement element = driver.findElement(By.cssSelector("#SubmitCreate font > font"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 10 | mouseOut | css=#SubmitCreate > span > font > font | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 11 | click | css=.account_creation:nth-child(1) > .page-subheading > font > font | 
    driver.findElement(By.cssSelector(".account_creation:nth-child(1) > .page-subheading > font > font")).click();
    // 12 | click | id=id_gender1 | 
    driver.findElement(By.id("id_gender1")).click();
    // 13 | click | id=customer_firstname | 
    driver.findElement(By.id("customer_firstname")).click();
    // 14 | type | id=customer_firstname | JOHN
    driver.findElement(By.id("customer_firstname")).sendKeys("JOHN");
    // 15 | click | id=customer_lastname | 
    driver.findElement(By.id("customer_lastname")).click();
    // 16 | type | id=customer_lastname | BELTRAN
    driver.findElement(By.id("customer_lastname")).sendKeys("BELTRAN");
    // 17 | click | id=passwd | 
    driver.findElement(By.id("passwd")).click();
    // 18 | runScript | window.scrollTo(0,700) | 
    js.executeScript("window.scrollTo(0,700)");
    // 19 | type | id=passwd | 123456
    driver.findElement(By.id("passwd")).sendKeys("123456");
    // 20 | click | id=days | 
    driver.findElement(By.id("days")).click();
    // 21 | select | id=days | label=regexp:2\s+
    {
      WebElement dropdown = driver.findElement(By.id("days"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:2\\s+']")).click();
    }
    // 22 | click | id=days | 
    driver.findElement(By.id("days")).click();
    // 23 | click | id=months | 
    driver.findElement(By.id("months")).click();
    // 24 | select | id=months | label=regexp:enero\s
    {
      WebElement dropdown = driver.findElement(By.id("months"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:enero\\s']")).click();
    }
    // 25 | click | id=months | 
    driver.findElement(By.id("months")).click();
    // 26 | click | id=years | 
    driver.findElement(By.id("years")).click();
    // 27 | select | id=years | label=regexp:2019\s+
    {
      WebElement dropdown = driver.findElement(By.id("years"));
      dropdown.findElement(By.xpath("//option[. = 'regexp:2019\\s+']")).click();
    }
    // 28 | click | id=years | 
    driver.findElement(By.id("years")).click();
    // 29 | click | css=.checkbox:nth-child(8) | 
    driver.findElement(By.cssSelector(".checkbox:nth-child(8)")).click();
    // 30 | click | id=newsletter | 
    driver.findElement(By.id("newsletter")).click();
    // 31 | click | id=optin | 
    driver.findElement(By.id("optin")).click();
    // 32 | click | id=company | 
    driver.findElement(By.id("company")).click();
    // 33 | type | id=company | Ath, ECCI,
    driver.findElement(By.id("company")).sendKeys("Ath, ECCI,");
    // 34 | click | id=address1 | 
    driver.findElement(By.id("address1")).click();
    // 35 | type | id=address1 | DG68D 70C37
    driver.findElement(By.id("address1")).sendKeys("DG68D 70C37");
    // 36 | click | id=address1 | 
    driver.findElement(By.id("address1")).click();
    // 37 | type | id=address1 | ECCI
    driver.findElement(By.id("address1")).sendKeys("ECCI");
    // 38 | click | id=address2 | 
    driver.findElement(By.id("address2")).click();
    // 39 | click | id=address1 | 
    driver.findElement(By.id("address1")).click();
    // 40 | type | id=address1 | DG 68D 70C31
    driver.findElement(By.id("address1")).sendKeys("DG 68D 70C31");
    // 41 | click | id=address2 | 
    driver.findElement(By.id("address2")).click();
    // 42 | click | id=address2 | 
    driver.findElement(By.id("address2")).click();
    // 43 | click | id=account-creation_form | 
    driver.findElement(By.id("account-creation_form")).click();
    // 44 | click | id=address2 | 
    driver.findElement(By.id("address2")).click();
    // 45 | type | id=address2 | DG 68D 70C38
    driver.findElement(By.id("address2")).sendKeys("DG 68D 70C38");
    // 46 | click | id=city | 
    driver.findElement(By.id("city")).click();
    // 47 | click | id=city | 
    driver.findElement(By.id("city")).click();
    // 48 | type | id=city | BOGOTA
    driver.findElement(By.id("city")).sendKeys("BOGOTA");
    // 49 | click | id=id_state | 
    driver.findElement(By.id("id_state")).click();
    // 50 | select | id=id_state | label=Hawai
    {
      WebElement dropdown = driver.findElement(By.id("id_state"));
      dropdown.findElement(By.xpath("//option[. = 'Hawai']")).click();
    }
    // 51 | click | id=id_state | 
    driver.findElement(By.id("id_state")).click();
    // 52 | click | id=postcode | 
    driver.findElement(By.id("postcode")).click();
    // 53 | type | id=postcode | 12456
    driver.findElement(By.id("postcode")).sendKeys("12456");
    // 54 | click | id=other | 
    driver.findElement(By.id("other")).click();
    // 55 | type | id=other | 15445454
    driver.findElement(By.id("other")).sendKeys("15445454");
    // 56 | click | id=phone | 
    driver.findElement(By.id("phone")).click();
    // 57 | type | id=phone | 3174336733  
    driver.findElement(By.id("phone")).sendKeys("3174336733  ");
    // 58 | click | id=phone_mobile | 
    driver.findElement(By.id("phone_mobile")).click();
    // 59 | type | id=phone_mobile | 4784526
    driver.findElement(By.id("phone_mobile")).sendKeys("4784526");
    // 60 | click | id=alias | 
    driver.findElement(By.id("alias")).click();
    // 61 | type | id=alias | My addressHOLA
    driver.findElement(By.id("alias")).sendKeys("My addressHOLA");
    // 62 | click | css=#submitAccount font > font | 
    driver.findElement(By.cssSelector("#submitAccount font > font")).click();
    // 63 | click | css=.info-account > font > font:nth-child(1) | 
    driver.findElement(By.cssSelector(".info-account > font > font:nth-child(1)")).click();
    // 64 | click | css=.page-heading > font > font | 
    driver.findElement(By.cssSelector(".page-heading > font > font")).click();
  }
}
