// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Caso5Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() throws MalformedURLException {
    driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), DesiredCapabilities.chrome());
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void caso5() {
    // Test name: caso#5
    // Step # | name | target | value
    // 1 | open | http://automationpractice.com/index.php | 
    driver.get("http://automationpractice.com/index.php");
    // 2 | setWindowSize | 1376x744 | 
    driver.manage().window().setSize(new Dimension(1376, 744));
    // 3 | click | css=.sfHover > .sf-with-ul | 
    driver.findElement(By.cssSelector(".sfHover > .sf-with-ul")).click();
    // 4 | runScript | window.scrollTo(0,289) | 
    js.executeScript("window.scrollTo(0,289)");
    // 5 | runScript | window.scrollTo(0,437) | 
    js.executeScript("window.scrollTo(0,437)");
    // 6 | runScript | window.scrollTo(0,700) | 
    js.executeScript("window.scrollTo(0,700)");
    // 7 | click | css=li:nth-child(1) > .subcategory-image .replace-2x | 
    driver.findElement(By.cssSelector("li:nth-child(1) > .subcategory-image .replace-2x")).click();
    // 8 | runScript | window.scrollTo(0,900) | 
    js.executeScript("window.scrollTo(0,900)");
    // 9 | click | css=.row:nth-child(3) | 
    driver.findElement(By.cssSelector(".row:nth-child(3)")).click();
    // 10 | click | css=li:nth-child(2) > .subcategory-image .replace-2x | 
    driver.findElement(By.cssSelector("li:nth-child(2) > .subcategory-image .replace-2x")).click();
    // 11 | runScript | window.scrollTo(0,600) | 
    js.executeScript("window.scrollTo(0,600)");
    // 12 | click | css=.product_img_link > .replace-2x | 
    driver.findElement(By.cssSelector(".product_img_link > .replace-2x")).click();
    // 13 | runScript | window.scrollTo(0,600) | 
    js.executeScript("window.scrollTo(0,600)");
    // 14 | click | css=.row:nth-child(3) | 
    driver.findElement(By.cssSelector(".row:nth-child(3)")).click();
  }
}
