// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CasodosTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void casodos() {
    driver.get("https://www.google.com/");
    driver.manage().window().setSize(new Dimension(745, 711));
    driver.findElement(By.name("q")).click();
    driver.findElement(By.name("q")).sendKeys("http://automationpractice.com/index.php");
    driver.findElement(By.name("q")).sendKeys(Keys.ENTER);
    {
      WebElement element = driver.findElement(By.cssSelector(".g > div > .rc .LC20lb"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".g > div > .rc .LC20lb > font > font")).click();
    driver.findElement(By.cssSelector("#contact-link font > font")).click();
    driver.findElement(By.cssSelector(".navigation_page > font > font")).click();
    driver.findElement(By.id("id_contact")).click();
    {
      WebElement dropdown = driver.findElement(By.id("id_contact"));
      dropdown.findElement(By.xpath("//option[. = 'Servicio al Cliente']")).click();
    }
    driver.findElement(By.id("id_contact")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("FAJARDOJAFB@GMAIL.COM");
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("FAJARDOJAFBGMAIL.COM");
    driver.findElement(By.id("id_order")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("FAJARDOJAFB@GMAIL.COM");
    driver.findElement(By.id("id_order")).click();
    driver.findElement(By.id("id_order")).sendKeys("112121GGGG2");
    driver.findElement(By.id("message")).click();
    driver.findElement(By.cssSelector("#submitMessage font > font")).click();
    driver.findElement(By.cssSelector(".alert")).click();
    driver.findElement(By.id("message")).click();
    driver.findElement(By.id("message")).sendKeys("GFHDHGHGHDGHR564656667&/&/&/&/");
    driver.findElement(By.cssSelector("#submitMessage font > font")).click();
    driver.findElement(By.cssSelector(".alert > font > font")).click();
    driver.findElement(By.cssSelector(".navigation_page > font > font")).click();
    driver.findElement(By.cssSelector(".alert")).click();
    driver.findElement(By.cssSelector("span:nth-child(1) > font:nth-child(2) > font")).click();
  }
}
